{
 "title": "Sentiment analysis",
 "time": { "from": "2023-06-27T14:24:48.286Z", "to": "2023-06-27T14:28:45.649Z" },
 "panels": [
  {
   "title": "Predictions and their correctness",
   "type": "timeseries",
   "description": "shows the total number of predictions and if they were predicted correctly",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "number_of_requests{app=\"model-service\"}",
     "legendFormat": "Number of predictions"
    },
    {
     "expr": "number_of_correct_predictions{app=\"model-service\", version=\"v1\"}",
     "legendFormat": "Correct predictions"
    },
    {
     "expr": "number_of_incorrect_predictions{app=\"model-service\"}",
     "legendFormat": "incorrect predictions"
    },
    {
     "expr": "number_of_requests-number_of_incorrect_predictions-number_of_correct_predictions",
     "legendFormat": "unknown predictions"
    }
   ]
  },
  {
   "title": "Accuracy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "number_of_correct_predictions/number_of_requests",
     "legendFormat": "Accuracy"
    }
   ]
  },
  {
   "title": "Participation of users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "(number_of_correct_predictions_1_0_0+number_of_incorrect_predictions_1_0_0)/number_of_requests_1_0_0",
     "legendFormat": "version 1"
    },
    {
     "expr": "(number_of_correct_predictions_1_1_0+number_of_incorrect_predictions_1_1_0)/number_of_requests_1_1_0",
     "legendFormat": "version 2"
    }
   ]
  },
  {
   "title": "Number of request in the last hour",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(number_of_requests[1h]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}