apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mymonitor
  labels:
    release: myprom
spec:
  selector:
    matchLabels:
      app: model-service-serv
  endpoints:
  - interval: 1s
    targetPort: 8080
    path: /metrics