apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: my-entry-service
spec:
  gateways:
    - my-gateway
  hosts:
    - "*"
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: app-serv
            subset: v1
          weight: 50
        - destination:
            host: app-serv
            subset: v2
          weight: 50
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: model-service
spec:
  hosts:
    - model-service-serv
  http:
  - route:
    - destination:
        host: model-service-serv
        subset: v1
      weight: 100
    mirror:
      host: model-service-serv
      subset: test