name: Helm Release
on:
  push:
    branches:
      - main
env:
  HELM_EXPERIMENTAL_OCI: 1 #enable OCI support
jobs:
  release-helm-chart:
    name: Release Helm Chart
    timeout-minutes: 90
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Registry Login (ghcr.io)
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Pushing Helm Chart
        run: |
          REPO=oci://ghcr.io/$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')/charts
          # create chart package for chart "sentimentchart"
          helm package sentimentchart
          # Get packed chart file name
          PKG_NAME=`ls *.tgz`
          helm repo index --url $REPO --merge index.yaml .
          helm push ${PKG_NAME} $REPO
