name: Helm Release
on:
  push:
    branches:
      - main
permissions:  write-all
jobs:
  release-helm-chart:
    name: Release Helm Chart
    timeout-minutes: 90
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Chart | Push
        uses: appany/helm-oci-chart-releaser@v0.3.0
        with:
          name: sentimentchart
          repository: operation
          tag: 0.1.0
          path: sentimentchart # Default charts/{name}
          registry: ghcr.io
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
